# Generated by Django 5.0.6 on 2024-07-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_comment_product_store_storeproduct_warehouse_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together={('warehouse', 'stock')},
        ),
    ]
