# Generated by Django 5.0.6 on 2024-07-05 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shops',
            options={'verbose_name': 'Мебельный салон', 'verbose_name_plural': 'Мебельные салоны'},
        ),
        migrations.AddField(
            model_name='shops',
            name='area',
            field=models.FloatField(default=0, verbose_name='Площадь магазина'),
        ),
        migrations.AddField(
            model_name='shops',
            name='deviation',
            field=models.IntegerField(null=True, verbose_name='Отклонение'),
        ),
        migrations.AddField(
            model_name='shops',
            name='fact',
            field=models.IntegerField(null=True, verbose_name='Факт выставленного товара'),
        ),
        migrations.AddField(
            model_name='shops',
            name='plan',
            field=models.IntegerField(null=True, verbose_name='Планируется выставить товара'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='name',
            field=models.CharField(max_length=254, verbose_name='Название магазина'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.shops', verbose_name='Мебельный салон')),
            ],
        ),
    ]
