# Generated by Django 5.0.6 on 2024-07-09 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_shops_options_shops_area_shops_deviation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='members',
            field=models.ManyToManyField(related_name='shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
