# Generated by Django 5.0.6 on 2024-07-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_shops_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=9, verbose_name='Артикул')),
                ('name', models.CharField(max_length=254, verbose_name='Номенклатура')),
                ('model', models.CharField(max_length=254, null=True, verbose_name='Модель')),
                ('manufacturer', models.CharField(max_length=254, null=True, verbose_name='Производитель')),
                ('squere', models.FloatField(null=True, verbose_name='Площадь номенклатуры')),
                ('category', models.CharField(max_length=254, null=True, verbose_name='Категория')),
                ('segment', models.CharField(max_length=254, null=True, verbose_name='Сегмент')),
                ('matrix', models.CharField(max_length=254, null=True, verbose_name='Матрица')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Склад')),
                ('warehouse_remains', models.IntegerField(null=True, verbose_name='Остатки склада')),
                ('product', models.ManyToManyField(null=True, related_name='Товар', to='reports.products')),
            ],
        ),
    ]
