# Generated by Django 5.0.6 on 2024-07-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_warehouseproduct_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='warehouseproduct',
            unique_together={('warehouse', 'product')},
        ),
    ]
