# Generated by Django 5.0.6 on 2024-07-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_products_warehouses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouses',
            name='product',
            field=models.ManyToManyField(related_name='Товар', to='reports.products'),
        ),
    ]
