# Generated by Django 5.0.6 on 2024-07-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_roomclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='area',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='general_plan_exhibition',
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='deviation',
            field=models.IntegerField(default=0, verbose_name='Отклонение'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='fact_exhibition',
            field=models.IntegerField(default=0, verbose_name='Факт выставки'),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='plan_exhibition',
            field=models.IntegerField(default=0, verbose_name='План выставки'),
        ),
    ]
