# Generated by Django 5.0.6 on 2024-07-09 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_comment_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='shop',
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.products', verbose_name='Товар'),
        ),
    ]
