# Generated by Django 5.0.6 on 2024-07-12 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_store_area_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeproduct',
            unique_together={('store', 'product')},
        ),
    ]
