# Generated by Django 5.0.6 on 2024-07-09 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_comment_shop_comment_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='product',
            field=models.ManyToManyField(related_name='Товары', to='reports.products'),
        ),
        migrations.AlterField(
            model_name='shops',
            name='members',
            field=models.ManyToManyField(related_name='Магазины', to=settings.AUTH_USER_MODEL),
        ),
    ]
