# Generated by Django 5.0.6 on 2024-07-15 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_storeproduct_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='warehouse',
        ),
    ]
