# Generated by Django 5.0.6 on 2024-07-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_shops_product_alter_shops_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shops',
            old_name='product',
            new_name='products',
        ),
    ]
