# Generated by Django 5.0.6 on 2024-07-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_remove_store_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
    ]
