# Generated by Django 5.0.6 on 2024-07-09 12:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_rename_product_shops_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Shops',
            new_name='Shop',
        ),
        migrations.RenameModel(
            old_name='Warehouses',
            new_name='Warehouse',
        ),
    ]
