# Generated by Django 5.0.6 on 2024-07-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_rename_products_product_rename_shops_shop_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Мебельный салон', 'verbose_name_plural': 'Мебельные салоны'},
        ),
        migrations.RemoveField(
            model_name='shop',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(related_name='shops', to='reports.shop'),
        ),
    ]
