# Generated by Django 5.0.6 on 2024-07-16 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(db_column='product_article', null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.product', verbose_name='Товар'),
        ),
    ]
