# Generated by Django 5.0.6 on 2024-07-12 06:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_shop_options_alter_warehouse_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shops',
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склад', 'verbose_name_plural': 'Склады'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='product',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_remains',
        ),
        migrations.AddField(
            model_name='comment',
            name='finish_planned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Название магазина')),
                ('area', models.FloatField(default=0, verbose_name='Площадь магазина')),
                ('users', models.ManyToManyField(blank=True, related_name='stores', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.store'),
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_plan_exhibition', models.IntegerField(blank=True, null=True)),
                ('plan_exhibition', models.IntegerField(blank=True, null=True, verbose_name='План выставки')),
                ('fact_exhibition', models.IntegerField(blank=True, null=True, verbose_name='Факт выставки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.store')),
            ],
            options={
                'verbose_name': 'Мебельный салон',
                'verbose_name_plural': 'Мебельные салоны',
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0, verbose_name='Остаток')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.warehouse')),
            ],
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
