# Generated by Django 5.0.6 on 2024-07-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_remove_product_shops_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Артикул'),
        ),
    ]
