# Generated by Django 5.0.6 on 2024-08-08 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='deviation',
        ),
        migrations.AlterField(
            model_name='product',
            name='room_class',
            field=models.CharField(blank=True, default='Нет класса', max_length=8, null=True, verbose_name='Класс комнаты'),
        ),
        migrations.AlterField(
            model_name='store',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='reports.city', verbose_name='Город'),
        ),
    ]
