# Generated by Django 5.0.6 on 2024-08-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_storeproduct_deviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproduct',
            name='plan_exhibition',
            field=models.IntegerField(default=0, verbose_name='План выставки'),
        ),
    ]
