# Generated by Django 5.0.6 on 2024-08-02 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='store',
        ),
    ]
